spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://ep-aged-rice-a4zs5cz6-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=${POSTGRESUSER}
spring.datasource.password=${POSTGRESPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver